# Generated by Django 4.2.6 on 2024-08-03 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='criado_em',
            new_name='data',
        ),
    ]
