# Generated by Django 4.2.6 on 2024-08-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_rename_criado_em_comentario_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='assunto',
            field=models.CharField(choices=[('', 'Selecione'), ('Adoção', 'Adoção'), ('Sugestões', 'Sugestões'), ('Elogios', 'Elogios'), ('Reclamações', 'Reclamações'), ('Outros', 'Outros')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='comentario',
            name='cidade',
            field=models.CharField(default='Informe sua cidade', max_length=50),
        ),
        migrations.AddField(
            model_name='comentario',
            name='mensagem',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='comentario',
            name='nome',
            field=models.CharField(default='Digite seu nome', max_length=50),
        ),
    ]
