# Generated by Django 4.2.6 on 2024-07-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_animal_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='descricao',
            field=models.TextField(default='Sem descrição'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='data_nascimento',
            field=models.DateField(default='2024-07-09'),
        ),
    ]
