# Generated by Django 4.2.6 on 2024-07-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='message',
            new_name='menssagem',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='amount',
            new_name='quantia',
        ),
    ]
