# Generated by Django 4.2.6 on 2024-07-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_rename_message_donation_menssagem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='menssagem',
            new_name='mensagem',
        ),
    ]
