# Generated by Django 4.2.6 on 2024-08-03 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('donations', '0004_doacao_delete_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='doador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
