# Generated by Django 4.2.6 on 2024-07-30 07:12

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('adote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adotaranimal',
            name='nome_adotante',
            field=models.CharField(default='Não Informado', max_length=100),
        ),
    ]