# Generated by Django 4.2.6 on 2024-08-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adote', '0002_add_nome_adotante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adotaranimal',
            name='estado_civil_adotante',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adotaranimal',
            name='nome_adotante',
            field=models.CharField(max_length=100),
        ),
    ]
