# Generated by Django 4.2.6 on 2024-08-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adote', '0003_alter_adotaranimal_estado_civil_adotante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adotaranimal',
            name='estado_civil_adotante',
            field=models.CharField(choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)')], max_length=50),
        ),
    ]
