# Generated by Django 4.2.6 on 2024-08-07 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0011_alter_animal_data_nascimento'),
        ('adote', '0004_alter_adotaranimal_estado_civil_adotante'),
    ]

    operations = [
        migrations.AddField(
            model_name='adotaranimal',
            name='animal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pet.animal'),
        ),
    ]
