# Generated by Django 4.2.6 on 2024-08-22 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0012_alter_animal_data_nascimento'),
        ('adote', '0006_rename_adotaranimal_adocao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adocao',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.animal'),
        ),
    ]
