# Generated by Django 4.2.6 on 2024-08-22 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adote', '0007_alter_adocao_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adocao',
            name='estado_civil_adotante',
        ),
        migrations.RemoveField(
            model_name='adocao',
            name='nome_adotante',
        ),
    ]
