# Generated by Django 4.2.6 on 2024-08-07 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('denuncia', '0002_denuncia_delete_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='denunciante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
